dist: xenial
os: linux
sudo: required
services:
- docker

language: go

go:
- master

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_install:
# Upgrade Docker
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
- scripts/ci/install_deps.sh

before_script:
- sudo minikube start --memory=4096 --vm-driver=none
- sudo chown -R $USER ${HOME}/.{mini,}kube

script:
# Build from scratch
- make workstation

# Test idempotency (no clobbering)
- make workstation

# Test teardown
- make clean

# Test teardown idempotency
- make clean

# Test destroy
- make destroy

