dist: xenial
os: linux
sudo: required
services:
- docker

before_install:
- docker verion

install:
- scripts/ci/install-deps.sh

jobs:
  include:
    - name: Verify minikube
      script:
      - minikube version

