dist: xenial
os: linux
sudo: required
services:
- docker

before_install:
# Upgrade Docker
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
- scripts/ci/install-deps.sh

jobs:
  include:
    - name: Verify minikube
      script:
      - minikube version

